// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97nVPMQ2oSo502wgPHewxcHaifEHMXA0',
    appId: '1:245035248880:web:d13dace6f7c1b8fca7a635',
    messagingSenderId: '245035248880',
    projectId: 'loyi-b530b',
    authDomain: 'loyi-b530b.firebaseapp.com',
    storageBucket: 'loyi-b530b.firebasestorage.app',
    measurementId: 'G-EHKF0FQPJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qyqwnGzew5pnE2f2A9tlINZ9MbO6LLw',
    appId: '1:245035248880:android:e85b269681555e98a7a635',
    messagingSenderId: '245035248880',
    projectId: 'loyi-b530b',
    storageBucket: 'loyi-b530b.firebasestorage.app',
  );

  // Added from ios/Runner/GoogleService-Info.plist (flutterfire's iOS step needs
  // the `xcodeproj` Ruby gem, which isn't set up on this machine).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Rb25AXT0zMurISVBOmfugu41EzCuJ_0',
    appId: '1:245035248880:ios:8e5eed339315b2dea7a635',
    messagingSenderId: '245035248880',
    projectId: 'loyi-b530b',
    storageBucket: 'loyi-b530b.firebasestorage.app',
    iosBundleId: 'be.loyi.loyi',
  );
}
